GitHub Actions to automate our GraphQL schema management
atom/github pull request #2108
Opened 2019-04-30 18:24 UTC by smashwilson

**Please be sure to read the [contributor's guide to the GitHub package](https://github.com/atom/github/blob/master/CONTRIBUTING.md) before submitting any pull requests.**

### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* Suggestion: You can use checklists to keep track of progress for the sections on metrics, tests, documentation, and user research.

### Description of the Change

Create [GitHub Actions](https://developer.github.com/actions/) to manage our local copy of the GitHub GraphQL schema in the least intrusive way I can think of.

* The first action, `schema-up`, will run weekly. It'll fetch the latest schema from GitHub and write it into the working directory. It'll then run the relay-compiler with the updated schema. If no generated Relay files have changed, the new schema will be committed and pushed directly onto `master`. If there _have_ been changes, the action will commit the schema and the Relay changes to a new branch, push it, open a pull request, and apply the "schema changed" label to it. (No pull request will be created if there's an existing open pull request with that label.)
* The second action, `schema-automerge`, will watch check suites and commit statuses arrive on the commits pushed to pull requests with the "schema changed" label. If they all report success, the pull request will be automatically merged.

### Screenshot

_N/A_

### Alternate Designs

We could have done this with our existing CI. Too late, this is more fun.

### Benefits

Ideally, this will give us an early warning for upcoming GraphQL deprecations that will cause issues for our package; the "schema-up" action will fail on its relay-compiler step if the schema has changed in an incompatible way. The action will also exclude deprecated fields, so we should see the notice before the schema change is made in production.

### Possible Drawbacks

It's hard to actually validate these until they run on real webhook triggers. They might be totally broken right now. I'll just have to fix any issues as they arise?

### Applicable Issues

_N/A_

### Metrics

_N/A_

### Tests

![image](https://user-images.githubusercontent.com/17565/56984225-863b4680-6b53-11e9-9f62-8853d1e424e4.png)

### Documentation

I've got READMEs in the source of both `./action` directories.

### Release Notes

_N/A_

### User Experience Research (Optional)

_N/A_

2019-05-01 13:53 UTC, smashwilson commented
I don't think there's any way for me to run this manually before we merge it into master. I'd feel better if someone other than me had a quick look at my source to find obvious bugs before I start running it, though 🙇

2019-05-01 17:46 UTC, kuychaco commented
Awesome, thanks so much for tackling this!

In the PR description it says:
> I've got READMEs in the source of both ./action directories.

I only see one directory `schema-up`. I'm assuming this comment is stale?

2019-05-01 18:22 UTC, smashwilson commented
Hah! Yes. I originally had another action that would automatically merge the schema-change pull requests if all check suites and commit statuses were green, but it was _super_ noisy - it added a check suite for every suite and status as it arrived. Edit'd 🙇

2019-05-01 21:57 UTC, kuychaco requested changes
This looks great! Excited to get our first GitHub Action in place, and be guarded against more regressions due to graphql API deprecations!

Thanks for putting this together @smashwilson ✨ 

Caught a few things that warrant attention :). 

I'd be curious if we could try out testing this prior to merging by temporarily changing the Actions trigger to be on push. We can always push empty commits if we need to. That could be a more efficient way of testing, and it'd be nice if all the changes were contained in a single PR for future reference.

2019-05-01 21:57 UTC, kuychaco commented on actions/schema-up/index.js
> +      repository(owner: $owner, name: repo) {
```suggestion
      repository(owner: $owner, name: $repo) {
```

2019-05-01 21:57 UTC, kuychaco commented on actions/schema-up/index.js
> +        pullRequests(first: 1, states: [OPEN], labels: ["schema update"]) {
Readability suggestion: Encapsulate the label information in an object. That way the relationship between the label name and id is explicit, and if we ever use a different label it'll be a more clear and straightforward to update the code.

```
const schemaUpdateLabel = {
  name: 'schema update',
  id: 'MDU6TGFiZWwxMzQyMzM1MjQ2'
}
```

```suggestion
        pullRequests(first: 1, states: [OPEN], labels: [schemaUpdateLabel.name]) {
```

along with corresponding change below for the label id

2019-05-01 21:57 UTC, kuychaco commented on actions/schema-up/index.js
> +  `, {id: createdPullRequest.id, labelIDs: ['MDU6TGFiZWwxMzQyMzM1MjQ2']});
See comment above for `schemaUpdateLabel`...

```suggestion
  `, {id: createdPullRequest.id, labelIDs: [schemaUpdateLabel.id]});
```

2019-05-01 21:57 UTC, kuychaco commented on actions/schema-up/index.js
> +    mutation CreatePullRequest($owner: String!, $repo: String!, $body: String!, $headRefName: String!) {
Looks like the required input for `createPullRequest` is:

<img width="562" alt="GraphQL_API_Explorer___GitHub_Developer_Guide" src="https://user-images.githubusercontent.com/7910250/57044103-42f9da00-6c1e-11e9-96d6-428d21e0c749.png">

So we also need `repositoryId` and `baseRefName`.

```suggestion
    mutation CreatePullRequest($repositoryId: ID!, $baseRefName: String!, $body: String!, $headRefName: String!) {
```

2019-05-01 21:57 UTC, kuychaco commented on actions/schema-up/index.js
> +        labelIds: []
```suggestion
        labelIds: $labelIDs
```

2019-05-01 21:57 UTC, kuychaco commented on actions/schema-up/index.js
> +}, {
Is it worth checking/logging that the label has been applied successfully? Maybe not a big deal...

2019-05-02 20:20 UTC, smashwilson commented
#2116 contains all of the testing output for this, with a minimal diff on the actual Actions code:

```diff
smashwilson @ hubtop ~/src/atom/github (aw/schema-update-action-test=)
$ git diff aw/schema-update-action -- actions/ .github/
diff --git a/.github/main.workflow b/.github/main.workflow
index 490262a3b..bb567a330 100644
--- a/.github/main.workflow
+++ b/.github/main.workflow
@@ -1,6 +1,8 @@
 workflow "GraphQL schema update" {
   // Every Monday at 1am.
-  on = "schedule(0 1 * * 1)"
+  // on = "schedule(0 1 * * 1)"
+
+  on = "push"
   resolves = "Update schema"
 }

diff --git a/actions/schema-up/index.js b/actions/schema-up/index.js
index db4c34f2b..6af28f367 100644
--- a/actions/schema-up/index.js
+++ b/actions/schema-up/index.js
@@ -87,6 +87,7 @@ The GraphQL schema has been automatically updated and \`relay-compiler\` has bee
     body += relayOutput;
     body += '\n```\n\nCheck out this branch to fix things so we don\'t break.';
   }
+  tools.log.info('Pull request body:\n%s', body);

   const createPullRequestMutation = await tools.github.graphql(`
     mutation createPullRequestMutation($repositoryId: ID!, $headRefName: String!, $body: String!) {
@@ -127,6 +128,7 @@ The GraphQL schema has been automatically updated and \`relay-compiler\` has bee
   tools.exit.success(
     `Pull request #${createdPullRequest.number} has been opened and labelled for this schema upgrade.`,
   );
+  tools.exit.success('Not creating pull request to reduce testing noise');
 }, {
   secrets: ['GITHUB_TOKEN'],
 });
```

2019-05-03 00:53 UTC, kuychaco approved these changes
Awesome work! 🚢 :shipit:

2019-05-03 00:53 UTC, kuychaco commented on actions/schema-up/index.js
> +        clientMutationId
Hmm it's a bit annoying that you're forced to ask for return data, even if there's no use for it...

2019-05-03 13:22 UTC, merged

2019-05-03 13:23 UTC, smashwilson commented
Thanks for the review 🙇 I guess we'll see it work live on Monday?